on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.13.0
      env:
        PAGES_BRANCH: gh-pages
        # BUILD_FLAGS: --drafts
        BUILD_THEMES: true
        TOKEN: ${{ secrets.TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
